# Generated by Django 6.0.7 on 2026-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_question_alter_customuser_phone_number_choice_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
